# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: 김희정
title: 성장하는 백엔드 개발자
email: khj960621@naver.com
website: www.github.com/hj0621

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username:  hj0621
instagram_username: iloveh2_

# Additional icon links
additional_links:
- title: Link name
  icon: fa-solid fa-blog (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
  url: https://blog.naver.com/glow_jung
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/me.jpg
about_content: | # this will include new lines to allow paragraphs
  안녕하세요, 저는 끈기와 결단력으로 성장하는 백엔드 개발자 김희정입니다. 

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: 구디 스크린골프
        link: github.com/codingwanee/HanaEZ-UP
        # link_text: Project Website
        additional_links:
          - title:  sproogen/modern-resume-theme
            icon: fab fa-github
            url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          My first project.
        description: | # this will include new lines to allow paragraphs
          JSP 기반으로 만든 저의 1차 프로젝트입니다. 스크린골프 예약 및 회원관리 사이트이며, 이 프로젝트 덕분에 많은 스킬들을 배우고 이해하였고 이를 바탕으로 2차 프로젝트를 진행했습니다.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: 구디아카데미
        caption: 2023.03 - 2023.08
        sub_title: 공공데이터 융합 자바/스프링 개발 양성과정
        quote: >
          저에게 있어서 구디아카데미는 코딩의 재미를 알려준 교육기관입니다.
        description: | # this will include new lines to allow paragraphs
          구디아카데미에서 교육과정을 밟으면서 존중과 협력에 대해 지향적인 자세를 갖게 되었으며 끈기와 결단력을 통해 어려운 상황에서도 포기하지 않고 문제를 해결하며, 개발자로서의 성장과 프로젝트의 성공에 큰 영향을 미칠 수 있다는 것을 깨닫게 되었습니다.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      관심사와 취미
      - 게임
      - 블로그

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
